name: Deploy to AWS

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0


      - name: Terraform Init
        run: cd Infrastructure && terraform init 

      - name: Terraform Apply
        run: cd Infrastructure && terraform apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Flask API to EC2
        run: |
          ssh -i ${{ secrets.PRIVATE_KEY }} ec2-user@34.245.182.58 'bash -s' << 'EOF'
            cd /path/on/ec2
            cd TestResultsHub/src
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            gunicorn -w 4 -b 0.0.0.0:5000 test-results-hub:app
          EOF
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          YOUR_APP: test-results-hub  # replace with your actual Flask app name

      - name: Terraform Destroy (Optional)
        if: ${{ github.event_name == 'pull_request' }}
        run: terraform destroy -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID=: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
