name: Deploy to AWS

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0


      - name: Terraform Init
        run: cd Infrastructure && terraform init 

      - name: Terraform Apply
        run: cd Infrastructure && terraform apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Code
        run: |
          # Add any deployment commands here

      - name: Terraform Destroy (Optional)
        if: ${{ github.event_name == 'pull_request' }}
        run: terraform destroy -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID=: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
